version: '3'

services:
  ssh-server:
    build: 
      dockerfile: server.Dockerfile
    container_name: ssh-server
    networks:
      - ssh-network

  ssh-client:
    build: 
      dockerfile: client.Dockerfile
    container_name: ssh-client
    networks:
      - ssh-network
    depends_on:
      - ssh-server
    tty: true
    stdin_open: true

networks:
  ssh-network:
    driver: bridge